### PR TITLE
Bookstore: initialize project with components

### PR DESCRIPTION
**Pull request by hajnaloltyan**
## Bookstore: initialize project with components

* [Live Demo](https://hajnaloltyan.github.io/react-bookstore/)

# 🎯 **_Milestones:_** 🏆

✔ Setup a new React application
✔ Create a directory  /components
✔ Install [React Router V6](https://reactrouter.com/en/main/start/tutorial#setup)
✔ Setup router inside of <App />
✔ Add 2 routes in the application
✔ Create components inside of the /components directory:

      * Contains individual book state, as well as a button to delete the book
      * Contains a list to renders individual books
      * Contains a form to create new books
      * Contains a navigation to link to the 2 routes

✔ IMPORTANT  replace category input with an author input

### 🎖 **General requirements:**

📌 No linter errors.
📌 Use of correct Gitflow.

### CODE REVIEW

**Review by rotimiazeez — COMMENTED** [review]
# Hi @hajnaloltyan, 

### While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project that is set up using `vite` instead of CRA(create react app). While I understand you want more efficiency, the project requirement state otherwise 😢. Kindly ensure your project is setup using CRA 👍🏽 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by hajnaloltyan** [comment]
Hi, I used Vite, because CRA is no longer the recommended way to create a React App, the links provided for this task and previous ones too that I'm happy to link here, all mention using Vite. I can also link projects from my peers that were created using Vite and got approved. 
Links inside this task:
* https://react.dev/learn/start-a-new-react-project#create-react-app
* https://reactrouter.com/en/main/start/tutorial#setup
* https://reactrouter.com/en/main/start/tutorial#adding-a-router


Inside previous To-Do App Tutorial: " _In this course, we will use Vite to create our projects._ "

**Review by OLIPLICHE — APPROVED** [review]
Hi @hajnaloltyan, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Highlights
- React-router-dom is present in package.json 👏
- It contains two pages of components: Books and Categories👏
- React router is set correctly 👏 👏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rotimiazeez** [comment]
Hi @hajnaloltyan, I understand you.
If it's up to me, I'd use vite as it's more efficient, and faster than CRA, but it the requirement for this project and I can't change that.
Screenshot_20230715_065111
Screenshot_20230715_065617
The CR that approved your friends PR risks getting sanctioned as it's stated clearly as you can see in the screenshot above. 👍🏼

**Pull request merged**
